server:
  port: 8888

spring:
  cloud:
    config:
      server:
          git:
            uri: https://github.com/JessiiPer/mercado-livre-microservice-repo
            search-paths:
            - url